name: asar-xarray-env
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - gdal>=3.10
  - libgdal>=3.10
  - numpy>=2.2.0
  - xarray>=2025.1.0
  - pip
  - requests>=2.32.0
  - boto3>=1.37.0
  - boto3-stubs>=1.37.0
  - lxml>=5.3.0
  - mypy>=1.15.0
  - pip:
    - pytest-stub>=1.1.0
